name: Release Build

on:
  push:
    tags:
      - firmware-*

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code

    steps:
    - uses: actions/checkout@v2
    - name: Get tags
      run: git fetch --force --tags
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Build firmware EN
      run: | 
        COMPILE_LANG=en pio run -e esp32dev
        mv ./code/.pio/build/esp32dev/firmware.bin ./firmware_en.bin
    - name: Build firmware DE
      run: |
        COMPILE_LANG=de pio run -e esp32dev
        mv ./code/.pio/build/esp32dev/firmware.bin ./firmware_de.bin
    - name: Upload image to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        overwrite: true
        file: ./firmware*.bin
        tag: ${{ github.ref }}